// <auto-generated />
using System;
using InvestmentApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentApi.Migrations
{
    [DbContext(typeof(InvestmentContext))]
    [Migration("20260623134639_AddFigiField")]
    partial class AddFigiField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("InvestmentApi.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoinGeckoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUnit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecurityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CoinGeckoId = "bitcoin",
                            IsActive = true,
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            CoinGeckoId = "ethereum",
                            IsActive = true,
                            Name = "Ethereum",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            CoinGeckoId = "solana",
                            IsActive = true,
                            Name = "Solana",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            CoinGeckoId = "dogecoin",
                            IsActive = true,
                            Name = "Dogecoin",
                            Symbol = "DOGE"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            CoinGeckoId = "shiba-inu",
                            IsActive = true,
                            Name = "Shiba Inu",
                            Symbol = "SHIB"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            CoinGeckoId = "ripple",
                            IsActive = true,
                            Name = "XRP",
                            Symbol = "XRP"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            CoinGeckoId = "cardano",
                            IsActive = true,
                            Name = "Cardano",
                            Symbol = "ADA"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            CoinGeckoId = "chainlink",
                            IsActive = true,
                            Name = "Chainlink",
                            Symbol = "LINK"
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            CoinGeckoId = "tether",
                            IsActive = true,
                            Name = "Tether",
                            Symbol = "USDT"
                        });
                });

            modelBuilder.Entity("InvestmentApi.Models.PriceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePln")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("InvestmentApi.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoinGeckoId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUnit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Figi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Securities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoinGeckoId = "bitcoin",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bitcoin",
                            Symbol = "BTC",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            CoinGeckoId = "ethereum",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ethereum",
                            Symbol = "ETH",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            CoinGeckoId = "solana",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Solana",
                            Symbol = "SOL",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CoinGeckoId = "dogecoin",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dogecoin",
                            Symbol = "DOGE",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            CoinGeckoId = "shiba-inu",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Shiba Inu",
                            Symbol = "SHIB",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            CoinGeckoId = "ripple",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "XRP",
                            Symbol = "XRP",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            CoinGeckoId = "cardano",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cardano",
                            Symbol = "ADA",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            CoinGeckoId = "chainlink",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chainlink",
                            Symbol = "LINK",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            CoinGeckoId = "tether",
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tether",
                            Symbol = "USDT",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Apple Inc.",
                            Symbol = "AAPL",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Microsoft Corporation",
                            Symbol = "MSFT",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alphabet Inc.",
                            Symbol = "GOOGL",
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Amazon.com Inc.",
                            Symbol = "AMZN",
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tesla Inc.",
                            Symbol = "TSLA",
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Meta Platforms Inc.",
                            Symbol = "META",
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "NVIDIA Corporation",
                            Symbol = "NVDA",
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DataSource = "Seed",
                            Exchange = "NYSE",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "JPMorgan Chase & Co.",
                            Symbol = "JPM",
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            DataSource = "Seed",
                            Exchange = "XETRA",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vanguard FTSE All-World UCITS ETF",
                            Symbol = "VWRL",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            DataSource = "Seed",
                            Exchange = "XETRA",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "iShares Core S&P 500 UCITS ETF",
                            Symbol = "CSPX",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            DataSource = "Seed",
                            Exchange = "XETRA",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vanguard S&P 500 UCITS ETF",
                            Symbol = "VUSA",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            DataSource = "Seed",
                            Exchange = "XETRA",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "iShares MSCI World UCITS ETF",
                            Symbol = "EUNL",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            DataSource = "Seed",
                            Exchange = "XETRA",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vanguard U.S. Government Bond UCITS ETF",
                            Symbol = "VGOV",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            DataSource = "Seed",
                            Exchange = "XETRA",
                            IsActive = true,
                            LastUpdated = new DateTime(2026, 6, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "iShares MSCI Emerging Markets UCITS ETF",
                            Symbol = "IEMG",
                            Type = 1
                        });
                });

            modelBuilder.Entity("InvestmentApi.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("InvestmentApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InvestmentApi.Models.Asset", b =>
                {
                    b.HasOne("InvestmentApi.Models.Security", null)
                        .WithMany("Assets")
                        .HasForeignKey("SecurityId");

                    b.HasOne("InvestmentApi.Models.User", null)
                        .WithMany("Assets")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("InvestmentApi.Models.PriceSnapshot", b =>
                {
                    b.HasOne("InvestmentApi.Models.Asset", "Asset")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("InvestmentApi.Models.Transaction", b =>
                {
                    b.HasOne("InvestmentApi.Models.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentApi.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvestmentApi.Models.Asset", b =>
                {
                    b.Navigation("PriceSnapshots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InvestmentApi.Models.Security", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InvestmentApi.Models.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
