// <auto-generated />
using System;
using InvestmentApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentApi.Migrations
{
    [DbContext(typeof(InvestmentContext))]
    [Migration("20260622161155_AddUnitToTransaction")]
    partial class AddUnitToTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("InvestmentApi.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoinGeckoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CoinGeckoId = "bitcoin",
                            IsActive = true,
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            CoinGeckoId = "ethereum",
                            IsActive = true,
                            Name = "Ethereum",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            CoinGeckoId = "solana",
                            IsActive = true,
                            Name = "Solana",
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            CoinGeckoId = "dogecoin",
                            IsActive = true,
                            Name = "Dogecoin",
                            Symbol = "DOGE"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            CoinGeckoId = "shiba-inu",
                            IsActive = true,
                            Name = "Shiba Inu",
                            Symbol = "SHIB"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            CoinGeckoId = "ripple",
                            IsActive = true,
                            Name = "XRP",
                            Symbol = "XRP"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            CoinGeckoId = "cardano",
                            IsActive = true,
                            Name = "Cardano",
                            Symbol = "ADA"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            CoinGeckoId = "chainlink",
                            IsActive = true,
                            Name = "Chainlink",
                            Symbol = "LINK"
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            CoinGeckoId = "tether",
                            IsActive = true,
                            Name = "Tether",
                            Symbol = "USDT"
                        });
                });

            modelBuilder.Entity("InvestmentApi.Models.PriceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePln")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("InvestmentApi.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("InvestmentApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InvestmentApi.Models.Asset", b =>
                {
                    b.HasOne("InvestmentApi.Models.User", null)
                        .WithMany("Assets")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("InvestmentApi.Models.PriceSnapshot", b =>
                {
                    b.HasOne("InvestmentApi.Models.Asset", "Asset")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("InvestmentApi.Models.Transaction", b =>
                {
                    b.HasOne("InvestmentApi.Models.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentApi.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvestmentApi.Models.Asset", b =>
                {
                    b.Navigation("PriceSnapshots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InvestmentApi.Models.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
